<?php
 require_once('pages\mod\header.php');
?>
  <body>
    <?php
        require_once('pages\mod\menu.php');
    ?>
    <?php
        require_once('pages\empresas\ofertas\table.ver_ofertas.php');
    ?>
  </body>
</html>