<?php
 require('Modularidad\header.php');
?>
  <body>
    <?php
        require('Modularidad\menu.php');
    ?>
    <?php
        require('Modularidad\ofertas_form\form.ofertas_form.php');
    ?>
  </body>
</html>