<?php
 require('Modularidad\header.php');
?>
  <body>
    <?php
        require('Modularidad\menu.php');
    ?>
    <?php
        require('Modularidad\perfil_usuario\content.perfil_usuario.php');
    ?>
  </body>
</html>