<?php
 require_once('pages\mod\header.php');
?>
  <body>
    <?php
        require_once('pages\mod\menu.php');
    ?>
    <?php
        require_once('pages\usuarios\index\content.index.php');
    ?>
  </body>
</html>